package com.aftership.sdk.model.tracking;

import lombok.Data;

/**
 * The param to identify the single tracking. Either id or (slug + tracking_number) should be *
 * specified.
 *
 * @author chenjunbiao
 */
@Data
public class SingleTrackingParam {
  /** A unique identifier generated by AfterShip for the tracking. */
  private String id;
  /** Unique code of courier */
  private String slug;
  /** Tracking number of a shipment. */
  private String trackingNumber;
  /** SingleTrackingOptionalParams is the optional parameters in single tracking query */
  private SingleTrackingOptionalParams optionalParams;
}
