package com.aftership.sdk.model.tracking;

import java.util.Date;
import java.util.List;
import java.util.Map;
import com.aftership.sdk.model.checkpoint.Checkpoint;
import lombok.Data;

/**
 * Tracking Object
 *
 * @link https://docs.aftership.com/api/4/trackings/post-trackings
 */
@Data
public class Tracking {
    /**
     * Date and time of the tracking created.
     * <p>DateTime</p>
     */
    private Date createdAt;
    /**
     * Date and time of the tracking last updated.
     * <p>DateTime</p>
     */
    private Date updatedAt;
    /**
     * A unique identifier generated by AfterShip for the tracking.
     * <p>String</p>
     */
    private String id;
    /**
     * The postal code of receiver's address. Required by some couriers, such asdeutsch-post
     * <p>String</p>
     */
    private String trackingPostalCode;
    /**
     * Shipping date inYYYYMMDDformat. Required by some couriers, such asdeutsch-post
     * <p>String</p>
     */
    private String trackingShipDate;
    /**
     * Account number of the shipper for a specific courier. Required by some couriers, such asdynamic-logistics
     * <p>String</p>
     */
    private String trackingAccountNumber;
    /**
     * Origin Country of the shipment for a specific courier. Required by some couriers, such asdhl
     * <p>String</p>
     */
    private String trackingOriginCountry;
    /**
     * Destination Country of the shipment for a specific courier. Required by some couriers, such aspostnl-3s
     * <p>String</p>
     */
    private String trackingDestinationCountry;
    /**
     * Located state of the shipment for a specific courier. Required by some couriers, such asstar-track-courier
     * <p>String</p>
     */
    private String trackingState;
    /**
     * Key of the shipment for a specific courier. Required by some couriers, such assic-teliway
     * <p>String</p>>
     */
    private String trackingKey;
    /**
     * Unique code of courier. Get courier slug here
     * <p>String</p>
     */
    private String slug;
    /**
     * Whether or not AfterShip will continue tracking the shipments. Value is false when tag (status) is Delivered,
     * Expired, or further updates for 30 days since last update.
     * <p>Boolean</p>
     */
    private boolean active;
    /**
     * Google cloud message registration IDs to receive the push notifications.
     * Accept either array or comma separated as input.
     * <p><b>Array or String</b></p>
     */
    private List<String> android;
    /**
     * Custom fields of the tracking.
     * <p><b>Hash</b></p>
     */
    private Map<String, String> customFields;
    /**
     * Customer name of the tracking.
     * <p>String</p>
     */
    private String customerName;
    /**
     * Total delivery time in days.
     * - Difference of 1st checkpoint time and delivered time for delivered shipments
     * - Difference of 1st checkpoint time and current time for non-delivered shipments
     * Value as 0 for pending shipments or delivered shipment with only one checkpoint.
     * <p>Number</p>
     */
    private int deliveryTime;
    /**
     * Destination country of the tracking. ISO Alpha-3 (three letters).
     * If you use postal service to send international shipments,
     * AfterShip will automatically get tracking results from destination postal service
     * based on destination country.
     * <p>String</p>
     */
    private String destinationCountryIso3;
    /**
     * Destination country of the tracking detected from the courier.
     * ISO Alpha-3 (three letters).
     * Value will be null if the courier doesn't provide the destination country.
     * <p>String</p>
     */
    private String courierDestinationCountryIso3;
    /**
     * Email address(es) to receive email notifications. Comma separated for multiple values.
     * <p>Array</p>
     */
    private List<String> emails;
    /**
     * Expected delivery date (nullable).
     * Available format:
     * YYYY-MM-DD,
     * YYYY-MM-DDTHH:MM:SS, or
     * YYYY-MM-DDTHH:MM:SS+TIMEZONE
     * <p>String</p>
     */
    private String expectedDelivery;
    /**
     * Apple iOS device IDs to receive the push notifications.
     * Accept either array or comma separated as input.
     * <p><b>Array or String</b></p>
     */
    private List<String> ios;
    /**
     * Text field for order ID
     * <p>order_id</p>
     */
    private String orderId;
    /**
     * Text field for order path
     * <p>String</p>
     */
    private String orderIdPath;
    /**
     * Origin country of the tracking. ISO Alpha-3 (three letters).
     * <p>String</p>
     */
    private String originCountryIso3;
    /**
     * The token to generate the direct tracking link:
     * https://yourusername.aftership.com/unique_token or
     * https://www.aftership.com/unique_token
     * <p>String</p>
     */
    private String uniqueToken;
    /**
     * Number of packages under the tracking (if any).
     * <p>Number</p>
     */
    private int shipmentPackageCount;
    /**
     * Shipment type provided by carrier (if any).
     * <p>String</p>
     */
    private String shipmentType;
    /**
     * Shipment weight provied by carrier (if any)
     * <p>Number</p>
     */
    private int shipmentWeight;
    /**
     * Weight unit provied by carrier, either in
     * kg or lb (if any)
     * <p>String</p>
     */
    private String shipmentWeightUnit;
    /**
     * Date and time the tracking was last updated
     * <p>DateTime</p>
     */
    private Date lastUpdatedAt;
    /**
     * Date and time the tracking was picked up
     * <p>DateTime</p>
     */
    private Date shipmentPickupDate;
    /**
     * Date and time the tracking was delivered
     * <p>DateTime</p>
     */
    private Date shipmentDeliveryDate;
    /**
     * Phone number(s) subscribed to receive sms notifications. Comma separated for multiple values
     * <p>Array</p>
     */
    private List<String> subscribedSmses;
    /**
     * Email address(es) subscribed to receive email notifications. Comma separated for multiple values
     * <p>Array</p>
     */
    private List<String> subscribedEmails;
    /**
     * Signed by information for delivered shipment (if any).
     * <p>String</p>
     */
    private String signedBy;
    /**
     * Phone number(s) to receive sms notifications.
     * The phone number(s) to receive sms notifications.
     * Phone number should begin with `+` and `Area Code` before phone number.
     * Comma separated for multiple values.
     * <p>Array</p>
     */
    private List<String> smses;
    /**
     * Source of how this tracking is added.
     * <p>source</p>
     */
    private String source;
    /**
     * Current status of tracking. Values include
     * Pending
     * InfoReceived
     * InTransit
     * OutForDelivery
     * AttemptFail
     * Delivered
     * AvailableForPickup
     * Exception
     * Expired
     * (See tag definition) @link https://docs.aftership.com/api/4/delivery-status
     * <p>String</p>
     */
    private String tag;
    /**
     * Current subtag of tracking. (See subtag definition)
     *
     * @link https://help.aftership.com/hc/en-us/articles/360007823253
     * <p>String</p>
     */
    private String subtag;
    /**
     * Normalized tracking message. (See subtag definition)
     *
     * @link https://help.aftership.com/hc/en-us/articles/360007823253
     * <p>String</p>
     */
    private String subtagMessage;
    /**
     * Title of the tracking.
     * <p>String</p>
     */
    private String title;
    /**
     * Number of attempts AfterShip tracks at courier's system.
     * <p>Number</p>
     */
    private int trackedCount;
    /**
     * Indicates if the shipment is trackable till the final destination.
     * Three possible values:
     * true
     * false
     * null
     * <p>Boolean or Null</p>
     */
    private Boolean lastMileTrackingSupported;
    /**
     * Store, customer, or order language of the tracking. ISO 639-1 Language Code .
     *
     * @link https://help.aftership.com/hc/en-us/articles/360001623287-Supported-Language-Parameters
     * <p>String or Null</p>
     */
    private String language;
    /**
     * Whether or not the shipment is returned to sender.
     * Value is true when any of its checkpoints has subtagException_010(returning to sender) orException_011
     * (returned to sender).
     * Otherwise value is false
     * <p><font color="red">Boolean</font></p>
     */
    private Boolean returnToSender;
    /**
     * Promised delivery date of an order inYYYY-MM-DDformat.
     * <p>String</p>
     */
    private String orderPromisedDeliveryDate;
    /**
     * Shipment delivery type
     * pickup_at_store
     * pickup_at_courier
     * door_to_door
     * <p>String</p>
     */
    private String deliveryType;
    /**
     * Shipment pickup location for receiver
     * <p>String</p>
     */
    private String pickupLocation;
    /**
     * Shipment pickup note for receiver
     * <p>String</p>
     */
    private String pickupNote;
    /**
     * Official tracking URL of the courier (if any)
     * <p>String</p>
     */
    private String courierTrackingLink;
    /**
     * date and time of the first attempt by the carrier to deliver the package to the addressee
     * Available format:
     * YYYY-MM-DDTHH:MM:SS, or
     * YYYY-MM-DDTHH:MM:SS+TIMEZONE
     * <p><font color="red">String or Null</font></p>
     */
    private String firstAttemptedAt;
    /**
     * Array of Hash describes the checkpoint information.
     * <p>Array of Checkpoint Object</p>
     */
    private List<Checkpoint> checkpoints;
}
